### ISSUE TITLE
Question: Packagist releases

### ISSUE THREAD

**Issue by jtgrimes** [zendtech/IbmiToolkit#37]
Any idea what needs to be done to get Packagist to recognize tags & releases? Right now, I'm having to pull in dev-master and set my minimum-stability to dev, which isn't my first choice.

It looks to me like everything is set up right - I'm wondering if one of the owners could take a look (if this seems like a legit issue to you).

**Comment by alanseiden** [comment]
Does it look like the same issue discussed by these good people?
https://github.com/PHPMailer/PHPMailer/issues/35
https://getcomposer.org/doc/02-libraries.md#specifying-the-version

Let me know what you're finding and I can dig into it or get additional help.

Alan

**Comment by ethali** [comment]
Same here. How can I ask Composer to install 1.5.1 for instance?
I need this version because dev-master is broken. Indeed now we have a makeDbCall method in the ToolkitService Class wich call

$this->db->execXMLStoredProcedure($this->conn, $sql)

The thing is that with an ODBC connection the execXMLStoredProcedure method has a mandatory third parameter!

**Comment by alanseiden** [comment]
I'm telling people to manually download the .zip of tagged release 1.6.1, which works. Don't use dev-master. It's in an unusable state.

**Comment by alanseiden** [comment]
Some of us are getting together at COMMON early next week to decide the fate of dev-master.

**Comment by alanseiden** [comment]
Older tagged releases are also available here.

**Comment by ethali** [comment]
Yes of course but I don't want to install it manually and older tags don't have a composer.json.
I just forked your repository and just maked a tag "1.6.2" from the "1.6.1" with just a composer.json file in it and it's OK.
So could you just make the same on this official repository? It would be really nice.

FYI I created a package for the Laravel framework so that we can develop using DB2 for i databases.
https://github.com/cooperl22/laravel-db2. For now I only tested it with an ODBC connection because pdo_ibm doesn't work on IBMi (Zend Server). By the way I sent a mail to you last few days because it seems you fixed the issue with this driver and I'm waiting from Shlomo Vanunu a compiled version for our IBMi server (ZS 6.3)...

I'm also making another package which includes your package (IbmiToolkit) and mine 'laravel-db2' so that we can develop webapps against IBMi (database and call programs).

**Comment by alanseiden** [comment]
Thanks for bringing this up. We're discussing among Zend and me. By the way, jtgrimes also uses Laravel on i. The two of you could share ideas.

**Comment by chukShirley** [comment]
Looks like this is resolved as of v1.7.0.
