### ISSUE TITLE
Default CA Bundle for HTTPS

### ISSUE THREAD

**Issue by phpdave** [zendtech/IbmiToolkit#46]
Talking with Chuk Shirley about the SSLCAFile and SSL/HTTPS in general. I suggested that this file (http://curl.haxx.se/ca/cacert.pem) be included in the toolkit and be used by default for https connecitons. This will keep things simple and easy for the users of the toolkit. They wouldn't need to go out and find it and set the SSLCAFile. I imagine a lot of IBMi shops will be below the PHP version 5.6. In PHP 5.6, SSL connections will by default use use the user's openssl default CA bundle - http://php.net/manual/en/migration56.openssl.php

I don't think there's a default CA bundle on the IBMi. If there is please let me know.

Related to https://github.com/zendtech/IbmiToolkit/pull/36

**Comment by chukShirley** [comment]
I want to say there is a default CA bundle (It uses Apache's), but that it's outdated. Could be wrong.

**Comment by adamculp** [comment]
Need to understand this more. Let's talk about this at ZendCon and decide. I don't want to reject it, or accept it, yet.

**Comment by alanseiden** [comment]
https://support.zend.com/hc/en-us/articles/205679027-Add-a-trusted-certificate-authority-to-IBM-i-for-PHP-5-6

**Comment by phpdave** [comment]
Oh so we should probably by default use this file: /QOpenSys/QIBM/ProdData/SC1/OpenSSL/openssl-0.9.7d/cert.pem

**Comment by clarkphp** [comment]
Yes, and the Zend Knowledge Base article Alan referred to was written
specifically to show where to obtain a current version and how to install
it.

Note the exact name of the openssl directory may differ from that in the
article, so follow the instructions closely, and create the correct
directory name.

The certificate bundle in question is typically provided on Linux
distributions by default, but this is naturally not the case for IBM i.

**Comment by alanseiden** [comment]
Including the bundle in the toolkit isn't a great answer because the bundle will need to change over time. Too much responsibility to bundle the bundle ourselves. Probably best approach is to document how to use bundles with PHP on IBM i. Note that PHP toolkit can also run on platforms other than IBM i (connecting to an i, of course). Linux/Windows may have their own bundles.

**Comment by adamculp** [comment]
I think I am also leaning toward including instructions in the README or perhaps some other method to "instruct" versus adding the cert that would require regular maintenance.

**Comment by phpdave** [comment]
I agree, we don't put the CA bundle in this repo.  

Might consider trying some default locations and possibly pull the file from the web.
https://gist.github.com/phpdave/8d594cfcfd6c11e704af .  Or just tell everyone to upgrade to PHP 5.6+.

**Comment by clarkphp** [comment]
Upgrading to PHP 5.6 is what will require everyone to install a CA bundle,
since PHP 5.6 by default requires peer certificate verification.  It was an
upgrade to PHP 5.6 in January that first exposed the need for a CA bundle
on IBM i.  A reference in the README to the Zend Knowledgebase article
mentioned previously is the simplest way to deal with this, in my opinion.
https://support.zend.com/hc/en-us/articles/205679027-Add-a-trusted-certificate-authority-to-IBM-i-for-PHP-5-6

**Comment by alanseiden** [comment]
Recognizing the value of Clark's last comment--that users should follow the KB article to install certs on IBM i, we are closing this issue.
