### ISSUE TITLE
Functions outside of class

### ISSUE THREAD

**Issue by adamculp** [zendtech/IbmiToolkit#5]
ToolkitService.php contains 3 functions that are not in the class.  These need to be moved to a class in some fashion.

getConfigValue() is already part of the class in that file.
logThis() should likely be a helper.
microDateTime() is only used once from within logThis().

**Comment by clarkphp** [comment]
I ran into this when working with the CW with a customer today.  Later I used the cwtest.php script as a guide for how to use the CW.  Since ToolkitService.php contains functions in the global namespace, as well as a class definition, autoloading doesn't help when the getConfigValue() function is called.  Needed to add a require_once 'ToolkitService.php', at least for now.

**Comment by alanseiden** [comment]
This example of getConfigValue():https://github.com/zendtech/IbmiToolkit/blob/57da8db1cc0ef77f835903a3a8cf691cbcdd3f28/ToolkitApi/ToolkitPCML.php#L74
could be change to refer to the class method with $this rather than the standalone function.
All other examples of standalone function getConfigValue() seem to be used by the CW. Unless end users came to rely on it!!
